"""
Watermark — Protection par watermark dans les résultats de trading
====================================================================

Intègre des informations d'identification dans les résultats du bot:
- Nom du client / ID licence visible dans les rapports
- Hash invisible dans les données de trading
- Permet de tracer les fuites et les partages non autorisés

Usage dans trading_engine_v4.py:
    from app.core.watermark import WatermarkManager
    wm = WatermarkManager(license_key="XXXX-XXXX", client_name="John Doe")
    report = wm.stamp_report(report_text)
    chart = wm.stamp_chart_data(trades_data)
"""

import hashlib
import json
from datetime import datetime
from typing import Optional, Dict, List


class WatermarkManager:
    """
    Gestionnaire de watermark pour SafeTrendBot.
    """

    def __init__(self, license_key: str, client_name: str = "", tier: str = "basic"):
        self.license_key = license_key
        self.client_name = client_name
        self.tier = tier
        self._watermark_hash = self._generate_hash()

    def _generate_hash(self) -> str:
        """Génère un hash unique basé sur la licence et la date."""
        raw = f"{self.license_key}{self.client_name}{datetime.utcnow().strftime('%Y%m')}"
        return hashlib.sha256(raw.encode()).hexdigest()[:16].upper()

    # ─────────────────────────────────────────────────────────────────────────
    # Watermark visible (rapports, UI)
    # ─────────────────────────────────────────────────────────────────────────

    def get_header(self) -> str:
        """Retourne le header à afficher dans les rapports."""
        return (
            f"\n{'='*60}\n"
            f"  SafeTrendBot V5 — {self.tier.upper()} Edition\n"
            f"  Licensed to: {self.client_name or 'Unnamed Client'}\n"
            f"  License ID: {self.license_key[:12]}...\n"
            f"  Hash: {self._watermark_hash}\n"
            f"{'='*60}\n"
        )

    def get_footer(self) -> str:
        """Retourne le footer à afficher."""
        return (
            f"\n{'='*60}\n"
            f"  Generated by SafeTrendBot V5\n"
            f"  © 2024 — All Rights Reserved\n"
            f"  Unauthorized distribution prohibited\n"
            f"{'='*60}\n"
        )

    def stamp_report(self, report_text: str) -> str:
        """Ajoute le watermark à un rapport texte."""
        return self.get_header() + "\n" + report_text + "\n" + self.get_footer()

    def stamp_telegram(self, message: str) -> str:
        """Ajoute un watermark discret aux messages Telegram."""
        # Embed invisible watermark (zero-width chars) in the text
        marked = self._embed_invisible(message)
        # Add visible footer
        footer = f"\n\n🔒 {self.client_name or 'SafeTrendBot User'} | {self.license_key[:8]}..."
        return marked + footer

    # ─────────────────────────────────────────────────────────────────────────
    # Watermark invisible (traçage)
    # ─────────────────────────────────────────────────────────────────────────

    def _embed_invisible(self, text: str) -> str:
        """Embed un watermark invisible dans le texte (zero-width chars)."""
        # Convert hash to zero-width chars
        zw_chars = {
            '0': '\u200B',  # Zero Width Space
            '1': '\u200C',  # Zero Width Non-Joiner
            '2': '\u200D',  # Zero Width Joiner
            '3': '\u2060',  # Word Joiner
            '4': '\uFEFF',  # Zero Width No-Break Space
            '5': '\u200B\u200C',
            '6': '\u200B\u200D',
            '7': '\u200C\u200D',
            '8': '\u200D\u2060',
            '9': '\u2060\uFEFF',
            'A': '\u200B\u2060',
            'B': '\u200C\uFEFF',
            'C': '\u200D\u200B',
            'D': '\u2060\u200C',
            'E': '\uFEFF\u200D',
            'F': '\u200B\u200C\u200D',
        }

        marker = ""
        for char in self._watermark_hash:
            marker += zw_chars.get(char, '')

        # Insert after first word
        words = text.split(' ')
        if len(words) > 1:
            words[0] = words[0] + marker
            return ' '.join(words)
        return text + marker

    @staticmethod
    def extract_invisible(text: str) -> Optional[str]:
        """Extrait le watermark invisible d'un texte."""
        # Extract zero-width chars
        zw_map = {
            '\u200B': '0', '\u200C': '1', '\u200D': '2', '\u2060': '3', '\uFEFF': '4',
        }

        extracted = ""
        for char in text:
            if char in zw_map:
                extracted += zw_map[char]

        if len(extracted) >= 16:
            return extracted[:16]
        return None

    # ─────────────────────────────────────────────────────────────────────────
    # Watermark dans les données (trades, CSV)
    # ─────────────────────────────────────────────────────────────────────────

    def stamp_csv(self, csv_lines: List[str]) -> List[str]:
        """Ajoute un watermark dans les données CSV."""
        # Add comment line with watermark
        header = f"# SafeTrendBot V5 | {self.license_key[:12]} | {self._watermark_hash}\n"
        return [header] + csv_lines

    def stamp_json(self, data: dict) -> dict:
        """Ajoute un watermark dans les données JSON."""
        data["_watermark"] = {
            "license_hash": self._watermark_hash,
            "version": "5.3.0",
            "tier": self.tier,
            "timestamp": datetime.utcnow().isoformat(),
        }
        return data

    def verify_json(self, data: dict) -> bool:
        """Vérifie que le watermark correspond à cette licence."""
        wm = data.get("_watermark", {})
        return wm.get("license_hash") == self._watermark_hash

    # ─────────────────────────────────────────────────────────────────────────
    # Screenshot watermark (optionnel)
    # ─────────────────────────────────────────────────────────────────────────

    def get_overlay_text(self) -> str:
        """Texte à superposer sur les screenshots/exports."""
        return f"STB5 | {self.client_name or 'User'} | {self.license_key[:8]}"


# ─────────────────────────────────────────────────────────────────────────────
# INTEGRATION DANS LE BOT
# ─────────────────────────────────────────────────────────────────────────────

def setup_watermark(license_key: str, client_name: str = "", tier: str = "basic") -> WatermarkManager:
    """Initialise le watermark manager pour le bot."""
    return WatermarkManager(license_key, client_name, tier)


# ─────────────────────────────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────────────────────────────

def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--license", required=True)
    parser.add_argument("--name", default="Test Client")
    parser.add_argument("--tier", default="basic")
    parser.add_argument("--text", default="Rapport de trading SafeTrendBot...")
    args = parser.parse_args()

    wm = WatermarkManager(args.license, args.name, args.tier)

    print(wm.get_header())
    print(f"Texte avec watermark invisible: {wm.stamp_telegram(args.text)[:100]}...")
    print(wm.get_footer())

    # Test extraction
    marked = wm.stamp_telegram(args.text)
    extracted = WatermarkManager.extract_invisible(marked)
    print(f"\nHash extrait: {extracted}")
    print(f"Match: {extracted == wm._watermark_hash}")


if __name__ == "__main__":
    main()
